displayName=Canoe Hotkeys
author=Blueue
description=Customizable hotkeys for selecting a canoe type at the canoe shaping dialog
tags=canoe,hotkey,woodcutting,travel
version=
plugins=com.canoehotkeys.CanoeHotkeysPlugin
build=standard
